# This is a minimal pubspec.yaml for the arvoituskortit UI.  It mirrors the
# upstream manifest from commit e5f882677617a327c4915bed61778983998ae276 and
# adds no additional dependencies.  Assets and fonts are retained so that the
# existing graphics and typefaces continue to work.  When building this app
# you should run `flutter pub get` inside the repository root.

name: arvoituskortit
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  share_plus: ^10.0.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.26
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/seed.json
  # Shaders are omitted here because Impeller requires valid GLSL 3.0, and
  # our app draws its aurora background procedurally in code rather than
  # loading custom fragment shaders.  Removing these prevents shader
  # compilation errors on build.  If custom shaders are added later, list
  # them here.
  fonts:
    - family: CanavaGrotesk
      fonts:
        - asset: assets/fonts/CanavaGrotesk-Regular.otf