# pubspec.yaml
name: arvoituskortit
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  share_plus: ^10.0.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.26
  flutter_shaders: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/seed.json
  shaders:
    - assets/shaders/smoke_background.frag
    - assets/shaders/glass_refract.frag
  fonts:
    - family: CanavaGrotesk
      fonts:
        - asset: assets/fonts/CanavaGrotesk-Regular.otf
